src/Autyan.NiChiJou.Blog/Controllers/ArticleController.cs
using System.Threading.Tasks;
using Autyan.NiChiJou.Blog.Models;
using Autyan.NiChiJou.Core.Context;
using Autyan.NiChiJou.Core.Service;
using Autyan.NiChiJou.DTO.Blog;
using Autyan.NiChiJou.Model.Blog;
using Autyan.NiChiJou.Service.Blog;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Autyan.NiChiJou.Blog.Controllers
{
    public class ArticleController : Controller
    {
        private readonly IArticleService _articleService;

        private readonly IIdentityContext<BlogIdentity> _identityContext;

        public ArticleController(IArticleService articleService,
            IIdentityContext<BlogIdentity> identityContext)
        {
            _articleService = articleService;
            _identityContext = identityContext;
        }

        [HttpGet("Article/Posts/{id:long}")]
        [AllowAnonymous]
        public async Task<IActionResult> GetArticleAsync(long id)
        {
            var article = await _articleService.ReadArticleDetailByIdAsync(id, HttpContext.Connection.RemoteIpAddress);
            if (article.Succeed)
            {
                return View(nameof(Article), article.Data);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Editor(ArticleEditorViewModel model)
        {
            ServiceResult<Article> result;
            if (model.Id == null)
            {
                result = await _articleService.CreateArticleAsync(new Article
                {
                    Id = model.Id,
                    Title = model.Title,
                    Extract = model.Extract,
                    BlogId = _identityContext.Identity.BlogId
                }, model.Content);
            }
            else
            {
                result = await _articleService.UpdateArticleAsync(new Article
                {
                    Id = model.Id,
                    Title = model.Title,
                    Extract = model.Extract,
                    BlogId = _identityContext.Identity.BlogId
                }, model.Content);
            }

            if (result.Succeed)
            {
                return Redirect($"/Article/Posts/{result.Data.Id}");
            }

            return Redirect("/");
        }

        [HttpGet]
        [AllowAnonymous]
        [Route("Article/Editor/{id:long}")]
        public async Task<IActionResult> Editor(long? id)
        {
            if (id != null)
            {
                var article = await _articleService.FindArticleAsync(id.Value);
                if (article.Succeed && article.Data.Id != null)
                {
                    var model = new ArticleEditorViewModel
                    {
                        Id = id.Value,
                        Title = article.Data.Title
                    };
                    var content = await _articleService.LoadArticleContentAsync(article.Data.Id.Value);
                    model.Content = content.Data;
                    return View(model);
                }

                return NotFound();
            }
            return View();
        }

        [HttpGet]
        [Route("Article/Editor")]
        public IActionResult Editor()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Comment(AddCommentViewModel model)
        {
            var comment = new ArticleComment
            {
                PostId = model.ArticleId,
                Content = model.Content
            };
            if (_identityContext.Identity != null)
            {
                comment.CommentedBy = _identityContext.Identity.UserId;
            }

            var result = await _articleService.AddCommentOnArticle(comment, _identityContext.Identity?.MemberCode, HttpContext.Connection.RemoteIpAddress);
            if (!result.Succeed)
            {
                return Json(result);
            }
            return Json(result.Data);
        }
    }
}

src/Autyan.NiChiJou.Blog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - のんびり毎日</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @RenderSection("Styles", required: false)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">のんびり毎日</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a asp-area="" asp-controller="Article" asp-action="Editor" asp-route-id="" class="navbar-brand">Post</a>
                    </li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()

    </div>
    <hr />
<footer>
    <div class="panel panel-default col-lg-6 col-lg-offset-3">
        <div class="panel-body">
            <span>Links </span>
            <a href="https://www.gu6s.top" title="顾兆慧的一生"><span class="label label-success">gu6s</span></a>
            <a href="https://yulaiz.com/" title="深圳地王"><span class="label label-success">YuLai'sBlog</span></a>
            <a href="http://sayyoulove.me/" title="深情的安总"><span class="label label-success">sayyoulove-me</span></a>
            <a href="https://blog.aquariuslt.com" title="Aquariuslt Blog"></a>
            <a href="https://wxsm.space" title="Kary Gor Blog"><span class="label label-success">Kary Blog</span></a>
            <a href="https://wxsm.space" title="九鼎五百万年终Java大内高手，c字楼Picado刚枪选手"><span class="label label-success">Lousama Blog</span></a>
            <a href="https://github.com/404NoFound" title="车底良哥"><span class="label label-success">NotFound404</span></a>
            <a href="http://ikoala.net" title="蛤交女大律师，未毕业进驻上海TOP5律所"><span class="label label-success">考拉的生活碎片</span></a>
            <a href="http://corydon.cc" title="新片厂未来的Android职业队长，不带耳机打cs,脑放挺声辩位把把吃鸡"><span class="label label-success">新片厂 13c</span></a>
            <a href="http://chjydu.com" title="ACM前区域金牌，世界未来的希望，口头禅是我来自黑马，请将我定义为智障"><span class="label label-success">CN RPMan</span></a>
            <a href="http://frankxfz.me" title="NLP guy"><span class="label label-success">Frank Xu</span></a>
            <a href="http://xuyuanxin.win" title="先有桃子后有天，阿狸出门跑飞天"><span class="label label-success">阿狸</span></a>
        </div>
    </div>
    <div class="col-lg-12">
        <p style="text-align: center;">&copy; 2018 - のんびり毎日, Powered By : <a href="https://www.asp.net/">asp.net core</a></p>
    </div>
</footer>
    <div class="modal fade" id="baseModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <h3 class="modal-title"></h3>
                </div>
                <div class="modal-body">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" id="modal-cancel" data-dismiss="modal"></button>
                    <button type="button" class="btn btn-primary" id="modal-confirm" style="display: none;">确认</button>
                </div>
            </div>
        </div>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>